export const ADD_LIST_REQUEST = "ADD_LIST_REQUEST";
export const ADD_LIST_SUCCESS = "ADD_LIST_SUCESS";
export const ADD_LIST_FAIL = "ADD_LIST_FAIL";

export const ADD_CREATE_REQUEST = "ADD_CREATE_REQUEST";
export const ADD_CREATE_SUCCESS = "ADD_CREATE_SUCESS";
export const ADD_CREATE_FAIL = "ADD_CREATE_FAIL";